#!/bin/bash
#
# pkg-remove: Deinstall a package.
#
# Copyright (C) 2012 Matias Moreno Meringer <mmoreno80@gmail.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

PROGRAM=$(basename $0)

usage ()
{
    STATUS=$1
    echo "Usage: $PROGRAM [OPTIONS] PACKAGE..."
    if [ $STATUS -eq 0 ]
    then
	echo
	echo "$PROGRAM removes an already installed PACKAGE. Prints to"
	echo "stdout each successfully removed package."
	echo
	echo "		--root DIR	Installation root directory."
	echo "		--lib DIR	Installation libraries directory."
	echo "		-h, --help      Show this help."
	echo
	echo "Copyright (c) 2012, Matias Moreno Meringer <mmoreno80@gmail.com>"
	echo "All rights reserved."
    fi
    exit $STATUS
}

error ()
{
    echo "error:" $* 1>&2
}

warn ()
{
    echo "warning:" $* 1>&2
}

die ()
{
    error "$@"
    exit 1
}

log ()
{
    logger -p user.notice -t $PROGRAM -- $@
}

remove_package ()
{
    echo -n "+ Removing $PACKAGE ... "
    for file in $(tac $LIB/$PACKAGE.installed)
    do
	if [ -d "$file" ]
	then
	    rmdir --ignore-fail-on-non-empty "$ROOT/$file" > /dev/null 2>&1
	else
	    rm -f "$ROOT/$file" > /dev/null 2>&1
	fi
    done
    mv $LIB/$PACKAGE.installed $LIB/$PACKAGE-$DATE.removed || die "cannot update installation log for $PACKAGE"
    echo "done."
}

TEMP=$(getopt -o hv -l help,root:,lib: -n "$PROGRAM" -- "$@")
[ $? -eq 0 ] || exit $?
eval set -- $TEMP
while :
do
    case "$1" in
	-h|--help) usage 0;;
	--root) ROOT="$2"; shift 2;;
	--lib) LIB="$2"; shift 2;;
	--) shift; break;;
	*) usage 1;;
    esac
done

if [ -z "$@" ]
then
    error "wrong number of arguments"
fi

ROOT=${ROOT:-/}
ROOT=$(realpath $ROOT)
LIB=${LIB:-$ROOT/var/lib/pkg}
LIB=$(realpath $LIB)

[ -d "$ROOT" ] || die "cannot find root directory $ROOT"
[ -d "$LIB" ] || die "cannot find lib directory $LIB"

for arg in "$@"
do
    if [ ! -e "$LIB/$arg.installed" ]
    then
	warn "cannot find package $arg"
    else
	PACKAGE="$arg"
	DATE=$(date +%Y%m%d)
	remove_package
	log "$PACKAGE"
    fi
done
